name: iamhere
description: "Trip advisor remake"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dio: ^5.9.0
  get_it: ^8.2.0
  drift: ^2.30.0
  drift_flutter: ^0.2.8
  path_provider: ^2.1.5
  flutter_bloc: ^9.1.1
  go_router: ^17.0.1
  slang: ^4.8.1
  slang_flutter: ^4.8.0
  getwidget: ^7.0.0
  shared_preferences:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  drift_dev: ^2.30.0
  build_runner: ^2.10.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/